### ISSUE TITLE
feature request: enable RSS

### ISSUE THREAD

**Issue by 19-10-9** [tomfran/typo#11]
could you please add the enableRSS feature?

**Comment by tomfran** [comment]
Sure I can look into it, also, if you already know how to do it and want to contribute, feel free to do so 👍🏻

**Comment by GigaArpit** [comment]
See:

* https://digitaldrummerj.me/hugo-create-rss-feed/
* https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/rss.xml

**Comment by ivan-avalos** [comment]
Hugo builds a RSS feed by default, simply add this to `head.html` in order to reference it:

```
{{ with .OutputFormats.Get "rss" -}}
  {{ printf `<link rel=%q type=%q href=%q title=%q>` .Rel .MediaType.Type .Permalink site.Title | safeHTML }}
{{ end }}
```

https://gohugo.io/templates/rss/
