### ISSUE TITLE
Deployment w/ GitHub Pages

### ISSUE THREAD

**Issue by wvirany** [tomfran/typo#20]
Hi,

I am having trouble deploying the website with GitHub pages. For example, I have followed the setup instructions and have the site working on my local machine. How can I make this my personal webpage?

Thanks for the help

**Comment by tomfran** [comment]
You can follow [this guide](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site) to setup a github.io domain page.

Then, your Hugo website project should contain a `/public` dir, this is the content that should go into the repo created following the guide. Pushing to it should deploy the running website.

In my [website repo](https://github.com/tomfran/blog), I have the public folder as a git submodule linking to the [website repo](https://github.com/tomfran/tomfran.github.io), this way, when I run `hugo`, the public folder gets updated. I can then just push this folder to have an updated website.

I saw that you have your Hugo project directly into your [*.github.io repo](https://github.com/wvirany/wvirany.github.io), which is wrong. Indeed this should contain the `/public` Hugo output.

Let me know if this makes sense.
