### ISSUE TITLE
Moving social icons to about page

### ISSUE THREAD

**Issue by wvirany** [tomfran/typo#21]
Hi,

I am trying to move my social icons from my home page:

![image](https://github.com/user-attachments/assets/22a05c6e-7072-4506-9d45-169ae00a8f6f)

To my about page: (preferably just before the news section)

![image](https://github.com/user-attachments/assets/0df9712b-1dc2-4e44-be21-3a411ed8fad0)

I tried moving this code:

```
{{ with site.Params.social }}
<div class="social-icons">
    {{- range . }}
    <a href="{{ trim .url " " | safeURL }}" target="_blank"
        rel="noopener noreferrer me"
        title="{{ (.title | default .name) | title }}">
        {{ partial "svg.html" . }}
    </a>
    {{- end }}
</div>
{{ end }}
```

from `home.html` in the `layouts/` directory of the theme to the `index.html` file in my 'about' folder (located in `contents/` at the top of my site. Evidently you can see the result. How can I achieve this? Thanks

(by the way, I love the theme! )

**Comment by wvirany** [comment]
Note: I achieved the result by doing something a bit hacky...

After the html was rendered in the `public` directory, I copied the code corresponding to the social icons into my about page. However, I'd like to do this the right way... by making it automatically include the socials I have in the config file

**Comment by tomfran** [comment]
Thank you for the kind comment about the theme!

Honestly, I was going to suggest your hacky solution. I believe you can't include Hugo constructs, such as that for loop, in a page content.

Perhaps your best bet would be to have a custom fork of the theme and modify `layouts/_default/single.html`  to have something like: 

```
if (about page) {
    render about.md content; 
    render social icons;
    render news part;
} else {
    ...
}
```

I don't think it's worth it in your case, as I believe your social icons would not change so frequently anyway.
