### ISSUE TITLE
Tags displayed as URL-Encoded in posts

### ISSUE THREAD

**Issue by Kosette** [tomfran/typo#4]
I test it in Chinese (I think this applys to many other URL-Encoded characters), while in posts tags are all displayed as raw URL-Encoded strings.

### Reproduction
Setting
```
tags: ["test","测试"]
showTags: true
```

### Screenshot
![image](https://github.com/tomfran/typo/assets/35268640/dbcd1df1-c53e-4e5a-ae39-14381a25a8d4)

I test it using `hugo server -D`

**Comment by tomfran** [comment]
Hi! 
Thank you for pointing out the issue. 

I'll look into it, in the meantime, do you have any ideas on what could be causing this?

**Comment by tomfran** [comment]
Hi! Thank you for submitting the issue. 
I looked into it and found out that I was passing the tag through the [urlize](https://gohugo.io/functions/urls/urlize/) function.

I just pushed a fix, let me know if you still see the issue.
