### ISSUE TITLE
Missing preview from Telegram / Whatsapp / Whatever

### ISSUE THREAD

**Issue by dag7dev** [tomfran/typo#46]
When using this template on a blog (I currently use it on my website), if I copy-paste a link, the preview is not generated in Telegram / WhatsApp.

It would be nice to have this thing fixed because it is better stylized when spreading links across the web.

**Comment by runofthemillgeek** [comment]
@dag7dev not sure I understand the problem you're having. My blog (https://blog.sangeeth.dev) is on c80f6e2 (latest commit) and the `og:image` is getting picked up correctly on WhatsApp and elsewhere. I don't think the position of those tags within `<head>` matters. Here's WhatsApp for example:

![CleanShot 2024-11-06 at 01 02 59@2x](https://github.com/user-attachments/assets/08dda67e-ba05-4276-9796-6df4fbc0e2c1)

**Comment by dag7dev** [comment]
sorry for the delay, here's what I mean: with this link https://dag7.it/posts/medium-is-it-worth-your-time-and-effort/

![image](https://github.com/user-attachments/assets/6e1d71bd-8711-4dd9-b0e2-3afeb41c19b3)

this is what is generated on Telegram

**Comment by runofthemillgeek** [comment]
Renders fine for me on Telegram too.

I don't see any `og:image` meta tags in the link you posted. Try updating Hugo and pull the latest typo theme version and see if it still has issues.

I also notice you have linked images from medium (https://miro.medium.com/). I'm not sure if Hugo's default opengraph templates pick up such external images for use in `og:image`. You could also try and see after updating the theme that the `images` array in frontmatter is populated with link to the same image you want to be featured. For example:

```md
---
title: Custom domains with HTTPS for your localhost servers on macOS
date: 2024-11-04T23:55:47+05:30
description: Goodbye http://localhost:5173 and hello https://vite.test ✨
images:
  - /posts/images/custom-domains-with-https-for-your-localhost-servers-on-macos-og-image.webp
tags:
  - tech
  - webdev
  - macos
draft: false
---
```

**Comment by dag7dev** [comment]
Thank you!
