### ISSUE TITLE
[Request] Bluesky & bookwyrm social icons

### ISSUE THREAD

**Issue by glottisfaun0000** [tomfran/typo#53]
Lot of people joining bluesky lately, would be good to have that icon. https://github.com/bluesky-social/social-app/blob/main/bskyembed/assets/logo.svg

Also, Bookwyrm https://joinbookwyrm.com/ https://github.com/bookwyrm-social/bookwyrm  https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/static/images/logo.png

It would be cool to have an option to use emoji. Also maybe consider these icon libraries:

https://pictogrammers.com/library/mdi/
https://simpleicons.org/

**Comment by tomfran** [comment]
Thank you for suggesting that website, I just added the full 3227 icons collection to the theme :)

About emojis, yes that could be nice, it could be done with a parameter on the icon to render the icon name instead of looking it up in the SVG definition. I'll update as soon as I have some time/

**Comment by glottisfaun0000** [comment]
Awesome, how would you reference one of the Simple Icons for a params.social icon?

**Comment by tomfran** [comment]
Yes, but how would it differ form the current implementation? Aside from renaming "name" to "icon"? Perhaps I'm missing something

**Comment by glottisfaun0000** [comment]
That's true. I'm also having trouble referencing some SimpleIcons by name, specifically ones with spaces. For example 
```
[[params.social]]
name = "Nintendo"
```

works

```
[[params.social]]
name = "Nintendo DS"
```

does not

**Comment by tomfran** [comment]
Well, if you look at the svg partial you see the name associated with each icon.

The name is the name of the SVG downloaded from this website https://simpleicons.org.

In your case, the Nintendo DS icon is simply named "nintendods".
