### ISSUE TITLE
Tiny error on the sample hugo.toml on wiki

### ISSUE THREAD

**Issue by kyagi** [tomfran/typo#7]
Hello, thank you for providing an awesome hugo theme. Soon after starting to use it, I became a big fan of it. Simple and clear is always the best! :-)

BTW, there seems to be a very tiny error on the sample of hugo.toml on your wiki. 

I found it when building my hugo site on Cloudflare Pages today. It seems that the Cloudflare Page building process cannot find the module if the value starts with the uppercase. So, would you fix it at your convenience, please?

```
before) theme = 'Typo'
after)  theme = 'typo'
```
https://github.com/tomfran/typo/wiki/Setup#21-site-config

Again, let me say thank you for your great work. I admire you both as an Engineer and a designer!
Have a good day!

**Comment by GigaArpit** [comment]
Faced same issue, and came here to open the same issue!

**Comment by tomfran** [comment]
Thank you so much for the kind words, glad you're enjoying the theme 😄
 
I always used the capitalized version on my repo, I don't know why it worked. I just updated the wiki.

**Comment by kyagi** [comment]
Your are right. As long as I run 'hugo' command on my Mac, it hasn't happened as well.
However, when it comes to deploying it on Cloudflare Pages, it fails. The version of hugo is v0.128.2 on both side.

Sorry for not exploring the build process on Cloudflare Pages side.
Anyway, this problem is resolved when I lowercase the first letter.
